/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int32_t i;
	uint32_t *pClcctrlreg =(uint32_t*) 0x40023830;
	uint32_t *pPortModereg =(uint32_t*)0x40020000;
	uint32_t *pPortOutreg =(uint32_t*) 0x40020014;
	//1. bat clock for GpioA in the AHB1ENR;
//	uint32_t temp = *pClcctrlreg; // read operation
//
//	temp= temp| 0x02; // modify
//	*pClcctrlreg = temp; // write back
	// thay 3 cau o muc 1 bang 1 cau duy nhat
	*pClcctrlreg |= (1<<0);

	//2. cau hinh che do in out pin:(mode of the IO pin)
	//a. clear the 10th 11th bit position

	*pPortModereg &= ~(1<<10);
	*pPortModereg &= ~(1<<11);
	//b. thay 2 cau tren bang mot cau
	*pPortModereg &= ~(3<<10); //vi 3 trong he nhi phan la 11




	//b. set the 10th bit position is 1
	*pPortModereg |= (1<<10);
	//3. Set 5th bit of output data register to  make I/O pin 5 High
	*pPortOutreg |= (1<<5);

    /* Loop forever */
	for(;;);
	while(1){

	}
}
