/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

void delay(void)
{
	for(uint32_t i =0 ; i < 400000 ; i++);

}

int main(void)
{

	uint32_t volatile *const pGPIOCModeReg  =  (uint32_t*)(0x40020800);
	uint32_t volatile *const pInPutDataReg  =  (uint32_t*)(0x40020800+0x10);
	uint32_t volatile *const pOutPutDataReg =  (uint32_t*)(0x40020800+0x14);
	uint32_t volatile *const pClockCtrlReg  =  (uint32_t*)(0x40023830);
	uint32_t volatile *const pPullupDownReg =  (uint32_t*)(0x40020800 + 0x0C);

	//1.Enable the peripheral clock of GPIOC peripheral
	*pClockCtrlReg |= ( 1 << 2);
	// 2.configure PC0,PC1,PC2,PC3 as output (rows)
	*pGPIOCModeReg &= ~(0xFF);//clear
	*pGPIOCModeReg |= 0x55;   //set
	// 3. configure PC10 , PC11, PC12, PC13 as input (columns)
	 *pGPIOCModeReg &= ~(0xFF << 20);
	 // 4.Enable internal pull-up resistors for PA12 PA13 PA14 PA15
	     *pPullupDownReg &= ~(0xFF << 20);
	     *pPullupDownReg |=  (0x55 << 20);


	     while(1)
	     {
	         //make all rows HIGH
	         *pOutPutDataReg |= 0x0f;

	         //make R1 LOW(PA0)
	         *pOutPutDataReg &= ~( 1 << 0);

	         //scan the columns
	         //check C1(PA10) low or high
	         if(!(*pInPutDataReg & ( 1 << 10))){
	         	//key is pressed
	         	delay();
	         	printf("1\n");
	         }

	         //check C2(PA11) low or high
	         if(!(*pInPutDataReg & ( 1 << 11))){
	         	//key is pressed
	         	delay();
	         	printf("2\n");
	         }

	         //check C3(PA12) low or high
	         if(!(*pInPutDataReg & ( 1 << 12))){
	         	//key is pressed
	         	delay();
	         	printf("3\n");
	         }

	         //check C4(PA13) low or high
	         if(!(*pInPutDataReg & ( 1 << 13))){
	         	//key is pressed
	         	delay();
	         	printf("4\n");
	         }


//	         //make all rows HIGH
//	          *pOutPutDataReg |= 0x0f;
//	         //make R2 LOW(PA1)
//	         *pOutPutDataReg &= ~( 1 << 1);
//
//	         //scan the columns
//	         //check C1(PA12) low or high
//	         if(!(*pInPutDataReg & ( 1 << 6))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("1\n");
//	   	         }
//
//	   	         //check C2(PA7) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 7))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("2\n");
//	   	         }
//
//	   	         //check C3(PA8) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 8))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("3\n");
//	   	         }
//
//	   	         //check C4(PA9) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 9))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("4\n");
//	   	         }
//
//	         //make all rows HIGH
//	          *pOutPutDataReg |= 0x0f;
//	         //make R3 LOW(PA2)
//	         *pOutPutDataReg &= ~( 1 << 2);
//	         //scan the columns
//			 //check C1(PA12) low or high
//	         if(!(*pInPutDataReg & ( 1 << 6))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("1\n");
//	   	         }
//
//	   	         //check C2(PA7) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 7))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("2\n");
//	   	         }
//
//	   	         //check C3(PA8) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 8))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("3\n");
//	   	         }
//
//	   	         //check C4(PA9) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 9))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("4\n");
//	   	         }
//
//
//	         //make all rows HIGH
//	          *pOutPutDataReg |= 0x0f;
//	         //make R4 LOW(PA3)
//	         *pOutPutDataReg &= ~( 1 << 3);
//
//	         //scan the columns
//	         //check C1(PA12) low or high
//	         if(!(*pInPutDataReg & ( 1 << 6))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("1\n");
//	   	         }
//
//	   	         //check C2(PA7) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 7))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("2\n");
//	   	         }
//
//	   	         //check C3(PA8) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 8))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("3\n");
//	   	         }
//
//	   	         //check C4(PA9) low or high
//	   	         if(!(*pInPutDataReg & ( 1 << 9))){
//	   	         	//key is pressed
//	   	         	delay();
//	   	         	printf("4\n");
//	   	         }


	     }//while end

	     }

