/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "main.h"

#include<stdint.h>


//	uint32_t *pClcctrlreg =(uint32_t*) 0x40023830;
//	uint32_t *pPortModereg =(uint32_t*)0x40020000;
//	uint32_t *pPortOutreg =(uint32_t*) 0x40020014;

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrlReg   = ADDR_AHB1ENR_REG;
	GPIOx_MODE_t  volatile *const pPortAModeReg = ADD_REG_GPIOA_MODE;
	GPIOx_ODR_t   volatile *const pPortAOutReg  = ADD_REG_GPIOA_OD;

	//1. enable the clock for GPOIA peripheral in the AHB1ENR (SET the 0rd bit position)
	pClkCtrlReg->gpioa_en = CLOCK_ENABLE;


	//2. configure the mode of the IO pin as output
	pPortAModeReg->pin_5 = MODE_CONF_OUTPUT;

	while(1)
	{
		//Set 12th bit of the output data register to make I/O pin-12 as HIGH
		pPortAOutReg->pin_5  = PIN_STATE_HIGH;

		//introduce small human observable delay
		//This loop executes for 300K times
		for(uint32_t i=0 ; i < 300000 ; i++ );

		//Reset 12th bit of the output data register to make I/O pin-12 as LOW
		pPortAOutReg->pin_5  = PIN_STATE_LOW;

		for(uint32_t i=0 ; i < 300000 ; i++ );
	}


	for(;;);
}
